version: '3.8'

services:
  frontend:
    # Définir le service frontend : Renseignement du Dockerfile à utiliser pour le front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Monter le répertoire de travail pour permettre le développement à chaud
      - .:/app
      # Préserver les modules node_modules pour éviter les conflits de permissions
      - /app/node_modules
    ports:
      # Mappe le port 4200 de l'hôte au port 4200 du conteneur
      - "4200:4200"
    # Commande pour démarrer le service Angular
    command: ["npm", "start"]
