# frontend/docker-compose.yaml
version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
